services:
  - type: web
    name: resumeci-payment-api
    runtime: node
    plan: free
    rootDir: ./payment-api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GENIUSPAY_PUBLIC_KEY
        value: pk_live_m8I9zvRmqZcv1GTkjcsqs97w0i8hclYL
      - key: GENIUSPAY_SECRET_KEY
        sync: false
      - key: GENIUSPAY_API_URL
        value: https://geniuspay.ci/api/v1/merchant/payments
